//
//  BookData.swift
//  MyApp
//
//  Created by greys on 10/22/24.
//

import Foundation

let allBooks: [Book] = [
    Book(id: UUID(), imageName: "acotar", title: "A Court of Thorns and Roses", author: "Sarah J. Maas", rating: 4.5, description: "When nineteen-year-old huntress Feyre kills a wolf in the woods, a terrifying creature arrives to demand retribution. Dragged to a treacherous magical land she knows about only from legends, Feyre discovers that her captor is not truly a beast, but one of the lethal, immortal faeries who once ruled her world. \n\nAt least, he's not a beast all the time. \n\nAs she adapts to her new home, her feelings for the faerie, Tamlin, transform from icy hostility into a fiery passion that burns through every lie she's been told about the beautiful, dangerous world of the Fae. But something is not right in the faerie lands. An ancient, wicked shadow is growing, and Feyre must find a way to stop it, or doom Tamlin-and his world-forever.", pages: 432, publisher: "Bloomsbury", isbn: "978-1619634442", released: "May 5, 2015", genres: ["Fantasy", "Romance"], numberOfRatings: 3107590, ratingsDistribution: [1307590, 900000, 400000, 300000, 200000], about: "Sarah J. Maas is the #1 bestselling author of the Throne of Glass, Court of Thorns and Roses, and Crescent City series. Her books have sold millions of copies and are published in thirty-eight languages. She lives in New York City with her family."),
    Book(id: UUID(), imageName: "br", title: "Beach Read", author: "Emily Henry", rating: 4.0, description: "A romantic comedy about two authors stuck in a beach house.", pages: 368, publisher: "Berkley", isbn: "978-0452290254", released: "May 19, 2020", genres: ["Romance"], numberOfRatings: 1448236, ratingsDistribution: [698236,450000,150000,100000, 50000], about: "Emily Henry is the #1 new york times and #1 sunday times bestselling author of funny story, happy place, book lovers, people we meet on vacation, and beach read. she lives and writes in the american midwest."),
    Book(id: UUID(), imageName: "atlwcns", title: "All the Light We Cannot See", author: "Anthony Doerr", rating: 5.0, description: "A Pulitzer Prize-winning novel set during World War II.", pages: 531, publisher: "Scribner", isbn: "978-1501173219", released: "May 6, 2014", genres: ["Historical Fiction"], numberOfRatings: 1448236, ratingsDistribution: [698236,450000,150000,100000, 50000], about: "Anthony Doerr is an American author of novels and short stories. He gained widespread recognition for his 2014 novel All the Light We Cannot See, which won the Pulitzer Prize for Fiction."),
    Book(id: UUID(), imageName: "tsoa", title: "The Song of Achilles", author: "Madeline Miller", rating: 4.5, description: "A modern retelling of the Iliad from the perspective of Patroclus.", pages: 368, publisher: "Ecco", isbn: "978-0062060624", released: "August 15, 2011", genres: ["Mythology", "Historical Fiction"], numberOfRatings: 1448236, ratingsDistribution: [698236,450000,150000,100000, 50000], about: "Madeline Miller grew up in New York City and Philadelphia. She attended Brown University, where she earned her BA and MA in Classics. She has taught and tutored Latin, Greek, and Shakespeare to high school students for over fifteen years. She has also studied at the University of Chicago’s Committee on Social Thought, and in the Dramaturgy department at Yale School of Drama, where she focused on the adaptation of classical texts to modern forms."),
    Book(id: UUID(), imageName: "dr", title: "Divine Rivals", author: "Rebecca Ross", rating: 4.8, description: "A gripping fantasy about love and rivalry during a war.", pages: 368, publisher: "Berkley", isbn: "978-0593642680", released: "April 4, 2023", genres: ["Fantasy"], numberOfRatings: 1448236, ratingsDistribution: [698236,450000,150000,100000, 50000], about: "Rebecca Ross is the #1 New York Times and Sunday Times bestselling author of fantasy books for teens and adults. She has written multiple highly acclaimed duologies, including LETTERS OF ENCHANTMENT, ELEMENTS OF CADENCE, and THE QUEEN’S RISING as well as two standalone novels: DREAMS LIE BENEATH and SISTERS OF SWORD & SONG. When not writing, she can be found in her garden where she plants wildflowers and story ideas. She resides in Northeast Georgia with her husband and her dog."),
    Book(id: UUID(), imageName: "lr", title: "Love Redesigned", author: "Lauren Asher", rating: 4.8, description: "A sweet and heartwarming romance.", pages: 384, publisher: "Bloom Books", isbn: "978-1737601605", released: "October 19, 2021", genres: ["Romance"], numberOfRatings: 1448236, ratingsDistribution: [698236,450000,150000,100000, 50000], about: "Lauren Asher is a New York Times, USA Today, Wall Street Journal, Sunday Times, Globe and Mail, and Publishers Weekly bestselling author of contemporary romance. She enjoys writing about flawed yet relatable characters you can’t help falling in love with and fictional worlds you wish were real."),
    Book(id: UUID(), imageName: "com", title: "Crown of Midnight", author: "Sarah J. Maas", rating: 4.8, description: "The second book in the Throne of Glass series.", pages: 432, publisher: "Bloomsbury", isbn: "978-1619633643", released: "August 27, 2013", genres: ["Fantasy"], numberOfRatings: 1448236, ratingsDistribution: [698236,450000,150000,100000, 50000], about: "Sarah J. Maas is the #1 bestselling author of the Throne of Glass, Court of Thorns and Roses, and Crescent City series. Her books have sold millions of copies and are published in thirty-eight languages. She lives in New York City with her family."),
    Book(id: UUID(), imageName: "tsys", title: "The Seven Year Slip", author: "Ashley Poston", rating: 4.8, description: "A whimsical love story that spans time.", pages: 336, publisher: "Quirk Books", isbn: "978-1683691577", released: "January 24, 2023", genres: ["Fantasy", "Romance"], numberOfRatings: 1448236, ratingsDistribution: [698236,450000,150000,100000, 50000], about: "Ashley Poston is the New York Times and USA Today best-selling author of The Dead Romantics, The Seven Year Slip, and A Novel Love Story. She has also written over half a dozen young adult novels. \n\nAfter graduating from the University of South Carolina with a BA in English, she pursued a career in the publishing industry where she helped design and implement marketing strategies for novels. Now, she writes full-time from her little grey house, and spoils her three cats. When not writing, she bides her time between South Carolina and New York, and all the bookstores between.")
   ]

   let recommendedBooks: [Book] = [
    Book(id: UUID(), imageName: "tog", title: "Throne of Glass", author: "Sarah J. Maas", rating: 4.8, description: "An epic fantasy adventure featuring a skilled assassin.", pages: 432, publisher: "Bloomsbury", isbn: "978-1619631250", released: "August 7, 2012", genres: ["Fantasy"], numberOfRatings: 1448236, ratingsDistribution: [698236,450000,150000,100000, 50000], about: "Sarah J. Maas is the #1 bestselling author of the Throne of Glass, Court of Thorns and Roses, and Crescent City series. Her books have sold millions of copies and are published in thirty-eight languages. She lives in New York City with her family."),
    Book(id: UUID(), imageName: "bl", title: "Book Lovers", author: "Emily Henry", rating: 4.2, description: "A charming story about love and the book industry.", pages: 368, publisher: "Berkley", isbn: "978-0593441254", released: "May 3, 2022", genres: ["Romance"], numberOfRatings: 1448236, ratingsDistribution: [698236,450000,150000,100000, 50000], about: "Emily Henry is the #1 new york times and #1 sunday times bestselling author of funny story, happy place, book lovers, people we meet on vacation, and beach read. she lives and writes in the american midwest."),
    Book(id: UUID(), imageName: "acosf", title: "A Court of Silver Flames", author: "Sarah J. Maas", rating: 4.47, description: "A powerful continuation of the A Court of Thorns and Roses series.", pages: 768, publisher: "Bloomsbury", isbn: "978-1635573868", released: "February 16, 2021", genres: ["Fantasy", "Romance"], numberOfRatings: 1448236, ratingsDistribution: [698236,450000,150000,100000, 50000], about: "Sarah J. Maas is the #1 bestselling author of the Throne of Glass, Court of Thorns and Roses, and Crescent City series. Her books have sold millions of copies and are published in thirty-eight languages. She lives in New York City with her family."),
    Book(id: UUID(), imageName: "bttm", title: "Better than the Movies", author: "Lynn Painter", rating: 4.7, description: "A delightful romantic comedy about high school love.", pages: 336, publisher: "Heartline Press", isbn: "978-1945940470", released: "May 3, 2022", genres: ["Romance"], numberOfRatings: 1448236, ratingsDistribution: [698236,450000,150000,100000, 50000], about: "Lynn Painter is the USA Today and New York Times Bestselling Author of BETTER THAN THE MOVIES. She writes romantic comedies for teens and adults, and when she isn't reading or writing, she can usually be found binge-watching rom-coms or shotgunning energy drinks."),
    Book(id: UUID(), imageName: "b13", title: "Binding 13", author: "Chloe Walsh", rating: 4.8, description: "A captivating new adult romance about love and friendship.", pages: 400, publisher: "Chloe Walsh", isbn: "978-1915624748", released: "October 1, 2021", genres: ["Romance", "New Adult"], numberOfRatings: 1448236, ratingsDistribution: [698236,450000,150000,100000, 50000], about: "Chloe Walsh is the bestselling author of The Boys of Tommen series, which exploded in popularity on TikTok, Goodreads, and Amazon. She has been writing and publishing New Adult and Adult contemporary romance for a decade. Her books have been translated into multiple languages. Animal lover, music addict, TV junkie, Chloe loves spending time with her family and is a passionate advocate for mental health awareness. Chloe lives in Cork, Ireland with her family.")
   ]

   let popularBooks: [Book] = [
    Book(id: UUID(), imageName: "rv", title: "Ruthless Vows", author: "Rebecca Ross", rating: 4.5, description: "The epic conclusion to the intensely romantic and beautifully written story that started in Divine Rivals. \n\nTwo weeks have passed since Iris Winnow returned home bruised and heartbroken from the front, but the war is far from over. Roman is missing, and the city of Oath continues to dwell in a state of disbelief and ignorance. When Iris and Attie are given another chance to report on Dacre’s movements, they both take the opportunity and head westward once more despite the danger, knowing it’s only a matter of time before the conflict reaches a city that’s unprepared and fracturing beneath the chancellor’s reign. \n\nSince waking below in Dacre’s realm, Roman cannot remember his past. But given the reassurance that his memories will return in time, Roman begins to write articles for Dacre, uncertain of his place in the greater scheme of the war. When a strange letter arrives by wardrobe door, Roman is first suspicious, then intrigued. As he strikes up a correspondence with his mysterious pen pal, Roman will soon have to make a decision: to stand with Dacre or betray the god who healed him. And as the days grow darker, inevitably drawing Roman and Iris closer together…the two of them will risk their very hearts and futures to change the tides of the war.", pages: 419, publisher: "Magpie", isbn: "0008588236", released: "December 26, 2023", genres: ["Historical Fiction", "Romance", "Fantasy"], numberOfRatings: 504318, ratingsDistribution: [318000,150000,30000,5000,33018], about: "Rebecca Ross is the #1 New York Times and Sunday Times bestselling author of fantasy books for teens and adults. She has written multiple highly acclaimed duologies, including LETTERS OF ENCHANTMENT, ELEMENTS OF CADENCE, and THE QUEEN’S RISING as well as two standalone novels: DREAMS LIE BENEATH and SISTERS OF SWORD & SONG. When not writing, she can be found in her garden where she plants wildflowers and story ideas. She resides in Northeast Georgia with her husband and her dog."),
    Book(id: UUID(), imageName: "sm", title: "Shatter Me", author: "Tahereh Mafi", rating: 4.5, description: "A gripping tale of a girl with a lethal touch.", pages: 368, publisher: "HarperCollins", isbn: "978-0062085504", released: "November 15, 2011", genres: ["Dystopian", "Fantasy"], numberOfRatings: 1448236, ratingsDistribution: [698236,450000,150000,100000, 50000], about: "Tahereh Mafi is the #1 New York Times bestselling, #1 international bestselling, and National Book Award-nominated author of over a dozen novels. The second installment in her new fantasy series, These Infinite Threads, is on shelves now. (She promises to update her website soon! Until then, most book news can be found on instagram.)"),
    Book(id: UUID(), imageName: "cc1", title: "Crescent City: House of Earth and Blood", author: "Sarah J. Maas", rating: 4.6, description: "An enthralling story of magic and love.", pages: 803, publisher: "Bloomsbury", isbn: "978-1635574049", released: "March 3, 2020", genres: ["Fantasy"], numberOfRatings: 1448236, ratingsDistribution: [698236,450000,150000,100000, 50000], about: "Sarah J. Maas is the #1 bestselling author of the Throne of Glass, Court of Thorns and Roses, and Crescent City series. Her books have sold millions of copies and are published in thirty-eight languages. She lives in New York City with her family."),
    Book(id: UUID(), imageName: "vch", title: "Verity", author: "Colleen Hoover", rating: 4.5, description: "A psychological thriller that will keep you on the edge of your seat.", pages: 340, publisher: "Montlake", isbn: "978-1542019669", released: "January 18, 2018", genres: ["Thriller", "Romance"], numberOfRatings: 1448236, ratingsDistribution: [698236,450000,150000,100000, 50000], about: "Colleen Hoover is the #1 New York Times bestselling author of twenty four novels and novellas. Hoover’s novels fall into the New Adult and Young Adult contemporary romance categories, as well as psychological thriller. \n\nColleen Hoover is published by Atria Books, Grand Central Publishing, Montlake Romance, and HarperCollins Publishers. \n\nIn 2015, Colleen’s novel CONFESS won the Goodreads Choice Award for Best Romance. That was followed up in 2016 with her latest title, It Ends With Us, also winning the Choice Award for Best Romance. In 2017, her title WITHOUT MERIT won best romance. \n\nHer novel CONFESS has been filmed as a series by Awestruck and is available on Prime Video via Amazon and iTunes. Katie Leclerc and Ryan Cooper star in the series."),
    Book(id: UUID(), imageName: "tuhm", title: "The Unhoneymooners", author: "Christina Lauren", rating: 4.4, description: "A hilarious romantic comedy about a wedding gone wrong.", pages: 368, publisher: "Gallery Books", isbn: "978-1501128035", released: "May 14, 2019", genres: ["Romance", "Comedy"], numberOfRatings: 1448236, ratingsDistribution: [698236,450000,150000,100000, 50000], about: "Christina Lauren is the combined pen name of long-time writing partners and best friends Christina Hobbs and Lauren Billings. The #1 international bestselling coauthor duo writes both Young Adult and Adult Fiction, and together has produced twenty New York Times bestselling novels.")
   ]
